import Head from 'next/head'
import Image from 'next/image'
import querystring from 'querystring'
import Dashboard from '../../components/dashboard';
import React, { useEffect, useState } from "react";
import queryString from 'querystring'



function Share() {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    const parsed = queryString.parse(location.search.slice(1));
    fetch("https://mooooodly.herokuapp.com/get_user?id="+parsed.id, {
      method: "GET"
    })
    .then((res) => res.json())
    .then((reponse) => {
      const responseData = reponse.data;
      setData(responseData)
      setLoading(false)
    }).catch((e) => {
      setLoading(false)
    })

  }, []);



  return (
    <>
      <Head>
        <title>Statify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          {(!isLoading && data) ?   <Dashboard responseData={data}/> :  <div className="w-screen h-screen flex justify-center items-center"><p>Loading...</p></div>  }
      </main>   
    </>
  )
}
export default Share;
